# Generated by Django 3.2.18 on 2023-06-07 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_auto_20230504_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='Placeholder', max_length=255, verbose_name='image'),
        ),
    ]
