# Generated by Django 3.2.18 on 2023-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
