# Generated by Django 3.2.18 on 2023-06-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0004_alter_genre_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='like_count',
            new_name='read_count',
        ),
    ]
